name: Backend Directus Extension Build

on:
  push:
    paths:
      - 'backend/Backend/directusExtensions/directus-extension-rocket-meals-bundle/src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/Backend/directusExtensions/directus-extension-rocket-meals-bundle

    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'
          registry-url: 'https://registry.npmjs.org'

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸš€ Build the extension
        run: npm run build

      - name: ğŸ” Check if build has changed
        id: check_changes
        run: |
          git diff --quiet dist/api || echo "changes"
        continue-on-error: true

      - name: ğŸ“¤ Commit and push changes if build has changed
        if: steps.check_changes.outputs.result == 'changes'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add dist/api
          git commit -m "Update build artifacts [skip ci]"
          git push origin HEAD:${{ github.ref }}
