name: Build & Submit iOS

on:
  push:
    branches: [master]
    paths:
      - 'frontend/app/**'
      - '.github/workflows/frontend_native_ios.yml'

jobs:
  build-ios:
    name: ğŸ iOS Build & Submit
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@v3

      - name: ğŸ§© Setup
        uses: ./.github/actions/setup-and-install

      - name: ğŸ Build & Submit
        run: |
          eas build --platform ios --non-interactive
          eas submit --platform ios --non-interactive --latest
        working-directory: ./frontend/app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
