name: GH-Pages Publish
on:
  push:
    branches:
      - master
    paths:
      - 'frontend/app/**'
      - ".github/workflows/frontend_web_ghpages_production.yml"

jobs:
  gh-pages:
    defaults:
      run:
        working-directory: ./frontend/app
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'
          registry-url: 'https://registry.npmjs.org'

      - name: ğŸ“¦ Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: ğŸ“› Git user config
        run: |
          git config --global user.name 'Rocket Meals'
          git config --global user.email 'nils@baumgartner-software.de'

      - name: ğŸš€ Deploy to GitHub Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          CI=false yarn deploy:gh:pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
