name: Screenshots CI Action

on:
  workflow_dispatch: # Allow manual triggering

  workflow_run:
    workflows: [ "pages-build-deployment" ]
    types:
      - completed

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Workflow Start
        run: echo "Screenshots CI Action workflow started"

  screenshots:
    runs-on: ubuntu-latest
    needs: start  # Dependent on the dummy job
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }} # Only run if manually triggered or pages build succeeded

    steps:
      - name: üèó Checkout Repository
        uses: actions/checkout@v3

      - name: üèó Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Install and Build
        run: npm install && npm run build
        working-directory: tools/screenshotGenerator

      - name: üì¶ Debug Environment Variables
        run: |
          echo "REPOSITORY_OWNER=${{ github.repository_owner }}"
          echo "REPOSITORY_NAME=${{ github.event.repository.name }}"
          echo "SCREENSHOT_DIR=${{ github.workspace }}/screenshots"

      - name: üöÄ Generate Screenshots
        run: npm run start
        working-directory: tools/screenshotGenerator
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          SCREENSHOT_DIR: ${{ github.workspace }}/screenshots

      - name: ‚òÅÔ∏è Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/screenshots
          name: ${{ github.event.repository.name }}-screenshots

      - name: Prevent Triggering Another Workflow
        if: github.event_name == 'deployment_status'
        run: |
          echo "Skipping CI run for screenshot upload"
          git update-index --skip-worktree screenshots/
