name: Frontend Setup and Install

on:
  workflow_dispatch:

jobs:
  setup:
    name: ğŸ— Setup & Install
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”„ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ§© Run shared setup
        uses: ./.github/actions/setup-and-install
