name: Expo Update Production
on:
  push:
    branches:
      - master
    paths:
      - 'frontend/app/**'
      - ".github/workflows/frontend_native_expo_production.yml"

jobs:
  update:
    name: EAS Update Production
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/app
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: ğŸ— Setup repository
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'
          registry-url: 'https://registry.npmjs.org'
      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸš€ Publish update to channel 'production'
        run: eas update --auto --platform all --non-interactive --channel production
