name: GH-Pages Deploy

on:
  push:
    branches: [master]
    paths:
      - 'frontend/app/**'
      - '.github/workflows/frontend_gh_pages.yml'

jobs:
  deploy-gh-pages:
    name: ğŸŒ Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-and-install

      - name: ğŸ“› Git user config
        run: |
          git config --global user.name 'Rocket Meals'
          git config --global user.email 'nils@baumgartner-software.de'

      - name: ğŸš€ Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          CI=false yarn deploy:gh:pages
        working-directory: ./frontend/app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
