name: Expo Combined - Update & Build

on:
  push:
    branches:
      - 'master'
    paths:
      - 'frontend/app/**'
      - ".github/workflows/frontend_native_expo_production.yml"

jobs:
  setup-and-install:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - name: âœ… Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN"
            exit 1
          fi

      - name: ğŸ§¾ Checkout repo
        uses: actions/checkout@v3

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'
          registry-url: 'https://registry.npmjs.org'

      - name: âš™ï¸ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: cd ./frontend/app && yarn install --frozen-lockfile

      - name: ğŸ’¾ Upload workspace
        uses: actions/upload-artifact@v3
        with:
          name: app-workspace
          path: frontend/app

  eas-update:
    needs: setup-and-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-workspace
          path: frontend/app
      - name: ğŸš€ Publish update
        run: cd ./frontend/app && eas update --auto --platform all --non-interactive --channel production
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  check-build-number-change:
    needs: setup-and-install
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - name: ğŸ§¾ Checkout (2 commits)
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: ğŸ” Compare build numbers
        id: check
        run: |
          old=$(git show HEAD^:frontend/app/app.config.ts | grep -A 5 'function getBuildNumber' | grep 'return' | grep -Eo '[0-9]+' | head -1 || echo "not-found")
          new=$(cat frontend/app/app.config.ts | grep -A 5 'function getBuildNumber' | grep 'return' | grep -Eo '[0-9]+' | head -1 || echo "not-found")
          echo "Old: $old, New: $new"
          if [ "$old" != "$new" ]; then echo "changed=true" >> $GITHUB_OUTPUT; else echo "changed=false" >> $GITHUB_OUTPUT; fi

  build-ios:
    needs: check-build-number-change
    if: needs.check-build-number-change.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-workspace
          path: frontend/app
      - name: ğŸ Build and Submit iOS
        run: |
          cd ./frontend/app
          eas build --platform ios --non-interactive
          eas submit --platform ios --non-interactive --latest
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  build-android:
    needs: check-build-number-change
    if: needs.check-build-number-change.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-workspace
          path: frontend/app
      - name: ğŸ¤– Build and Submit Android
        run: |
          cd ./frontend/app
          eas build --platform android --non-interactive
          eas submit --platform android --non-interactive --latest
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  build-android-preview:
    needs: check-build-number-change
    if: needs.check-build-number-change.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-workspace
          path: frontend/app
      - name: ğŸ§ª Build Android Preview
        run: cd ./frontend/app && eas build --platform android --non-interactive --profile previewApk
