name: Expo Build
on:
  push:
    branches:
      - native_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: ðŸ— Setup repo
        uses: actions/checkout@v3

      - name: ðŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'
          registry-url: 'https://registry.npmjs.org'

      - name: ðŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ðŸ“¦ Install dependencies
        run: cd ./frontend/app && npm ci

      - name: ðŸš€ Build iOS app
        run: cd ./frontend/app && eas build --platform ios --non-interactive

      - name: Get iOS build URL
        id: get-ios-build-url
        run: echo "iOS_BUILD_URL=$(eas build:list --platform ios --status finished --limit 1 --json | jq -r '.[0].artifacts.buildUrl')" >> $GITHUB_ENV

      - name: ðŸ“¤ Submit iOS build
        run: cd ./frontend/app && eas submit --platform ios --url ${{ env.iOS_BUILD_URL }} --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: ðŸš€ Build Android app - previewApk
        run: cd ./frontend/app && eas build --platform android --non-interactive --profile previewApk

      - name: ðŸš€ Build Android app - production
        run: cd ./frontend/app && eas build --platform android --non-interactive

      - name: Get Android build URL
        id: get-android-build-url
        run: echo "ANDROID_BUILD_URL=$(eas build:list --platform android --status finished --limit 1 --json | jq -r '.[0].artifacts.buildUrl')" >> $GITHUB_ENV

      - name: ðŸ“¤ Submit Android build
        run: cd ./frontend/app && eas submit --platform android --url ${{ env.ANDROID_BUILD_URL }} --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}