name: Expo Build
on:
  push:
    branches:
      - native_build
    paths:
      - 'frontend/app/**'
      - ".github/workflows/frontend_native_expo_build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'
          registry-url: 'https://registry.npmjs.org'

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: cd ./frontend/app && npm ci

      - name: ğŸš€ Build app
        run: cd ./frontend/app && eas build --non-interactive

      - name: ğŸ“¤ Submit iOS build
        run: cd ./frontend/app && eas submit --platform ios --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¤ Submit Android build
        run: cd ./frontend/app && eas submit --platform android --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
